In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Smartphones_cleaned_dataset.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.40,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.60,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,motorola,Motorola Moto Edge S30 Pro,34990,83.0,True,False,False,snapdragon,8.0,3.00,...,120,3,1.0,android,64.0,16.0,0,NaN,1080,2460
976,honor,Honor X8 5G,14990,75.0,True,False,False,snapdragon,8.0,2.20,...,60,3,1.0,android,48.0,8.0,1,1024.0,720,1600
977,poco,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,True,True,True,dimensity,8.0,2.85,...,144,3,1.0,android,64.0,16.0,0,NaN,1080,2460
978,motorola,Motorola Moto G91 5G,19990,80.0,True,True,False,snapdragon,8.0,2.20,...,60,3,1.0,android,108.0,32.0,1,1024.0,1080,2400
979,samsung,Samsung Galaxy M52s 5G,24990,74.0,True,False,False,NaN,8.0,NaN,...,60,3,1.0,android,64.0,32.0,1,1024.0,1080,2400

In [ ]:
# 1. How many unique smarphone brands are present?
n = df["brand_name"].nunique()

print(f"There are {n} unique brands in dataset")

There are 46 unique brands in dataset

In [ ]:
#2 .what is the average price of smartphones?

avg = df["price"].mean()
print(f"Avrage price of phone is {avg}")

Avrage price of phone is 32520.504081632655

In [ ]:
#3 .Which smartphone has the highest price?

p = df["price"].max()


highest = df[df["price"] == df["price"].max()]
highest = highest["brand_name"][427]
print(f"{highest} smartphone has the highest price")

vertu smartphone has the highest price

In [ ]:
#4 . what is the most common processor brand?

p = df["processor_brand"].mode()
print(f"the most common processor brand is {p}")

the most common processor brand is 0    snapdragon
Name: processor_brand, dtype: object

In [ ]:
#5 what is the average rating of smartphones?

r = df["rating"].mean()
print(f"the avrage rating of phone is {r}")

the avrage rating of phone is 78.25824800910125

In [ ]:
#6 what brand has the most models listed?
model = df["model"].value_counts().idxmax()
print(f"{model} brand has the most models listed")

Samsung Galaxy M52s 5G brand has the most models listed

In [ ]:
#7 Count of smarphones supporting 5G ?

count = df["has_5g"].value_counts()
count = count[True]
print(f"{count} smarphones supporting 5G")

549 smarphones supporting 5G

In [ ]:
df["has_5g"].value_counts()

has_5g
True     549
False    431
Name: count, dtype: int64

In [ ]:
#8 Average RAM across all the smartphones?

ram = round(df["ram_capacity"].mean())
print(f"Average RAM across all the smartphones is {ram}")

Average RAM across all the smartphones is 7

In [ ]:
#9 Which phone has the largest battery?

battery = df[df["battery_capacity"] == df["battery_capacity"].max()]
battery = battery["model"][843]
print(f"{battery} phone has the largest battery")

Doogee V Max phone has the largest battery

In [ ]:
df.columns

Index(['brand_name', 'model', 'price', 'rating', 'has_5g', 'has_nfc',
       'has_ir_blaster', 'processor_brand', 'num_cores', 'processor_speed',
       'battery_capacity', 'fast_charging_available', 'fast_charging',
       'ram_capacity', 'internal_memory', 'screen_size', 'refresh_rate',
       'num_rear_cameras', 'num_front_cameras', 'os', 'primary_camera_rear',
       'primary_camera_front', 'extended_memory_available', 'extended_upto',
       'resolution_width', 'resolution_height'],
      dtype='object')

In [ ]:
#10 MOst commmon screen refresh rate?

rate = df["refresh_rate"].mode()
print(f"the most comman refresh rate is {rate} ")

the most comman refresh rate is 0    60
Name: refresh_rate, dtype: int64

In [ ]:
#11 what's the average number pf rear cameras?
avg = df["num_rear_cameras"].mean()
print(f"the average number pf rear cameras is {avg}")

the average number pf rear cameras is 2.8142857142857145

In [ ]:
#12 HOw many smarphones suppost fast charging?
df["fast_charging"]

0      100.0
1       33.0
2       15.0
3        NaN
4       67.0
       ...
975     68.0
976     22.0
977     67.0
978      NaN
979      NaN
Name: fast_charging, Length: 980, dtype: float64

In [ ]:
#13 What is the average processor speed?

speed = df["processor_speed"].mean()
print(f"average processor speed is {speed}")

average processor speed is 2.427217484008529

In [ ]:
#14 Which OS is used by most smartphones?

os = df["os"].value_counts().idxmax()
print(f"{os} os is used by most smartphones ")

android os is used by most smartphones

In [ ]:
#15 How namy smartphones have an IR blaster?
ir = df["has_ir_blaster"].value_counts()
ir = ir[True]
print(f"{ir} smartphones have an IR blaster")

159 smartphones have an IR blaster

In [ ]:
#16 What is the correlation between RAM and price?

df["ram_capacity"].corr(df["price"])

np.float64(0.3860016700183043)

In [ ]:
#17 Top 5 most expensive phones (brand + model) ?
df[["brand_name","model","price"]].sort_values(by = "price",ascending = False).head()

    brand_name                                   model   price
427      vertu                   Vertu Signature Touch  650000
887     xiaomi  Xiaomi Redmi K20 Pro Signature Edition  480000
478     huawei        Huawei Mate 50 RS Porsche Design  239999
951     huawei        Huawei Mate 30 RS Porsche Design  214990
458     xiaomi                     Xiaomi Mi Mix Alpha  199990

In [ ]:
#18 Average front camera megapixels?

camera = round(df["primary_camera_front"].mean())
print(f"Average front camera megapixels is {camera}")

Average front camera megapixels is 17

In [ ]:
#19 Do all smartphones support extended memory?

support = df["extended_memory_available"].sum()
all = len(df)
if support == all:
  print("all smartphones support extended memory")
else:
  print("do not all smartphones support extended memory")
  print(f"{support} smartphones support extended memory")

do not all smartphones support extended memory
618 smartphones support extended memory

In [ ]:
#20 Distribution of phones by resolution width?

df["resolution_width"].value_counts().head()

resolution_width
1080    593
720     206
1440     61
1170     16
1600     11
Name: count, dtype: int64

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/pokemon_data.csv")

In [ ]:
df

,id,name,base_experience,height,weight,types,abilities,moves,stats
0,1,bulbasaur,64,7,69,"grass, poison","overgrow, chlorophyll","razor-wind, swords-dance, cut, bind, vine-whip","hp=45, attack=49, defense=49, special-attack=6..."
1,2,ivysaur,142,10,130,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=60, attack=62, defense=63, special-attack=8..."
2,3,venusaur,236,20,1000,"grass, poison","overgrow, chlorophyll","swords-dance, cut, bind, vine-whip, headbutt","hp=80, attack=82, defense=83, special-attack=1..."
3,4,charmander,62,6,85,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=39, attack=52, defense=43, special-attack=6..."
4,5,charmeleon,142,11,190,fire,"blaze, solar-power","mega-punch, fire-punch, thunder-punch, scratch...","hp=58, attack=64, defense=58, special-attack=8..."
...,...,...,...,...,...,...,...,...,...
1297,10273,ogerpon-wellspring-mask,275,12,398,"grass, water",water-absorb,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1298,10274,ogerpon-hearthflame-mask,275,12,398,"grass, fire",mold-breaker,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1299,10275,ogerpon-cornerstone-mask,275,12,398,"grass, rock",sturdy,"swords-dance, slam, vine-whip, double-kick, ta...","hp=80, attack=120, defense=84, special-attack=..."
1300,10276,terapagos-terastal,90,3,160,normal,tera-shell,"headbutt, body-slam, take-down, double-edge, roar","hp=95, attack=95, defense=110, special-attack=..."
1301,10277,terapagos-stellar,90,17,770,normal,teraform-zero,"headbutt, body-slam, take-down, double-edge, roar","hp=160, attack=105, defense=110, special-attac..."

In [ ]:
df.columns

Index(['id', 'name', 'base_experience', 'height', 'weight', 'types',
       'abilities', 'moves', 'stats'],
      dtype='object')

In [ ]:
df["name"].count()

np.int64(1302)

In [ ]:
# Get the Pokémon(s) with the maximum height
tallest_pokemon = df[df["height"] == df["height"].max()]
tallest_name = tallest_pokemon["name"].values[0]
print(tallest_name)

eternatus-eternamax

In [ ]:
df.values[0]

array([1, 'bulbasaur', 64, 7, 69, 'grass, poison',
       'overgrow, chlorophyll',
       'razor-wind, swords-dance, cut, bind, vine-whip',
       'hp=45, attack=49, defense=49, special-attack=65, special-defense=65, speed=45'],
      dtype=object)

In [ ]:
df["types"].value_counts()

types
normal            86
water             84
electric          52
grass             49
psychic           47
                  ..
psychic, ice       1
ice, rock          1
fighting, fire     1
grass, water       1
grass, rock        1
Name: count, Length: 221, dtype: int64

In [ ]:
# how many water type pockemon available
t = "water"
types = df[df["types"] == t ].count()
print(f"{types.values[1]} water type pockemon available")

84 water type pockemon available

In [ ]:
df[df["height"] == df["height"].max()]

,id,name,base_experience,height,weight,types,abilities,moves,stats
1214,10190,eternatus-eternamax,563,1000,0,"poison, dragon",pressure,"fly, flamethrower, hyper-beam, solar-beam, toxic","hp=255, attack=115, defense=250, special-attac..."

In [ ]:
name = df[df["base_experience"] == df["base_experience"].max()]
name["name"].values[0]

'blissey'

In [ ]:
df["abilities"].value_counts()

abilities
levitate                                    36
static, lightning-rod                       19
shields-down                                14
beast-boost                                 11
protosynthesis                              10
                                            ..
curious-medicine, own-tempo, regenerator     1
frisk, harvest                               1
keen-eye, vital-spirit, no-guard             1
own-tempo                                    1
neuroforce                                   1
Name: count, Length: 707, dtype: int64

In [ ]:
ab = "protosynthesis"
df[df["abilities"] == ab ].count().values[1]

np.int64(10)

In [ ]:
df["abilities" ].value_counts().idxmax()

'levitate'